.TH HAX\-CREATE 1 hax hax "HAX COMMAND INTERFACE MANUAL"

.SH NAME
hax \- a tool to create HAX websites and web components quickly.

.SH SYNOPSIS
hax [options] [command]

.SH DESCRIPTION
HAX seeks to be the smallest possible back-end CMS to make HAX work and be able to build websites with it. Leveraging JSON Outline Schema, HAX is able to author multiple pages, which it then writes onto the file system. This way a slim server layer is just for basic authentication, knowing how to save files, and placing them in version control.

This command line tool can be used to create and modify two different HAX based file structures. Web components (essentially custom HTML tags) using Lit or HAX Single-Sites (a single website editable in the browser with the CMS tools)

.SH COMMANDS
.PP
.B start
\- Select which hax sub\-program to run
.PP
.B update
[options] \- hax cli self update
.PP
.B serve
\- Launch HAXsite in development mode (http://localhost)
.PP
.B site
[options] [action] \- create or administer a HAXsite
.RS
Actions to perform on site include:
.RS
.B start
\- Launch site in browser (http://localhost)
.br
.B serve
\- Launch site in development mode
.br
.B node:stats
\- Node Stats / data
.br
.B node:add
\- Add a new page
.br
.B node:edit
\- Edit a page
.br
.B node:delete
\- Delete a page
.br
.B site:stats
\- Site Status / stats
.br
.B site:items
\- Site items
.br
.B site:items\-import
\- Import items (JOS / site.json)
.br
.B site:list\-files
\- List site files
.br
.B site:theme
\- Change theme
.br
.B site:element
\- Add new Lit component to custom/src
.br
.B site:html
\- Full site as HTML
.br
.B site:md
\- Full site as Markdown
.br
.B site:schema
\- Full site as HAXElementSchema
.br
.B site:sync
\- Sync git repo
.br
.B site:rsync
\- Rsync site to remote/local directory
.br
.B site:surge
\- Publish site to Surge.sh
.br
.B site:netlify
\- Publish site to Netlify
.br
.B site:vercel
\- Publish site to Vercel
.br
.B setup:github\-actions
\- Setup GitHub Actions deployment
.br
.B setup:gitlab\-ci
\- Setup GitLab CI deployment
.br
.B recipe:read
\- Read recipe file
.br
.B recipe:play
\- Play recipe file
.br
.B issue:general
\- Issue: Submit an issue or suggestion
.br
.B issue:theme
\- Issue: Suggest custom theme
.RE
.RE
.PP
.B wc | webcomponent
[options] [action] \- Create Lit based web components, with HAX recommendations
.RS
Actions to perform on web component include:
.RS
.B start
\- Launch project
.br
.B wc:stats
\- Check status of web component
.br
.B wc:element
\- Add new Lit component to existing project
.br
.B wc:haxproperties
\- Write haxProperties schema
.RE
.RE
.PP
.B audit
[options] \- Audits web components for compliance with DDD (HAX design system)
.PP
.B party
[options] [action] \- Party time! Join the HAX community and get involved!
.RS
Actions to perform include:
.RS
.B test
\- Test action
.RE
.RE
.PP
.B help
[command] \- display help for command

.SH OPTIONS
.TP
\--v
Verbose output
.TP
\--debug
output for developers
.TP
\--format <char>
output format; json (default), yaml
.TP
\--path <char>
where to perform operation
.TP
\--name <char>
name of the project/web component
.TP
\--npm\-client <char>
npm client to use (must be installed) npm, yarn, pnpm (default: "npm")
.TP
\--y
yes to all questions
.TP
\--skip
skip frills like animations
.TP
\--quiet
remove console logging
.TP
\--auto
yes to all questions, alias of y
.TP
\--no\-i
prevent interactions / sub\-process, good for scripting
.TP
\--to\-file <char>
redirect command output to a file
.TP
\--no\-extras
skip all extra / automatic command processing
.TP
\--root <char>
root location to execute the command from
.TP
\--org <char>
organization for package.json
.TP
\--author <char>
author for site / package.json
.TP
\--writeHaxProperties
write haxProperties for the element
.TP
\--force
force creation even if name exists in registry
.TP
\--import\-site <char>
URL of site to import
.TP
\--import\-structure <char>
import method to use:
.br
pressbooksToSite
.br
elmslnToSite
.br
haxcmsToSite
.br
notionToSite
.br
gitbookToSite
.br
evolutionToSite
.br
htmlToSite
.br
docxToSite
.TP
\--node\-op <char>
node operation to perform
.TP
\--item\-id <char>
node ID to operate on
.TP
\--domain <char>
published domain name
.TP
\--title\-scrape <char>
CSS Selector for `title` in resource
.TP
\--content\-scrape <char>
CSS Selector for `body` in resource
.TP
\--items\-import <char>
import items from a file / site
.TP
\--recipe <char>
path to recipe file
.TP
\--custom\-theme\-name <char>
custom theme name
.TP
\--custom\-theme\-template <char>
custom theme template; (options: base, polaris\-flex, polaris\-sidebar)
.TP
\--source <char>
rsync source directory or remote path
.TP
\--destination <char>
rsync destination directory or remote path
.TP
\--exclude <char>
comma\-separated patterns to exclude from rsync
.TP
\--dry\-run
perform rsync dry run
.TP
\--delete
delete extraneous files from destination
.TP
\--repos <char...>
repositories to clone
.TP
\-V, \--version
output the version number
.TP
\--title <char>
title
.TP
\--content <char>
page content
.TP
\--slug <char>
path (slug)
.TP
\--published <char>
publishing status
.TP
\--tags <char>
tags
.TP
\--parent <char>
parent
.TP
\--order <char>
order
.TP
\--theme <char>
theme
.TP
\--hide\-in\-menu <char>
hide in menu
.TP
\-h, \--help
display help for command

.SH EXAMPLES
.TP
.B hax start
Navigatable interface to select which hax sub\-program to run
.TP
.B hax site mysite \--y
Create a new HAXsite (HAXcms, single site) with automatic yes to all questions
.TP
.B hax site mysite \--path /var/www \--author "John Doe"
Create a new HAXsite in a specific path with custom author
.TP
.B hax webcomponent my\-element \--y
Make a new HAX capable, i18n wired, design system (DDD) driven web component
.TP
.B hax wc my\-button \--org @mycompany \--author "Developer Name"
Create a web component with specific organization and author
.TP
.B hax serve
Launch HAXsite in development mode (http://localhost)
.TP
.B hax site site:theme \--theme polaris\-flex
Change the theme of an existing site
.TP
.B hax site node:add \--title "New Page" \--content "Page content"
Add a new page to an existing site
.TP
.B hax audit \--debug
Audit web components for compliance with DDD (HAX design system) with debug output
.TP
.B hax party \--repos haxtheweb/webcomponents
Join the HAX community by cloning specific repositories
.TP
.B hax update \--y
Update HAX CLI to the latest version automatically

.SH BUGS
Bugs can be viewed at GitHub Issues: https://github.com/haxtheweb/issues/issues

Bugs can also be submitted through Merlin on a HAX Site (in the browser) by typing "Issue" to jump start a report!

.SH EXTRA
.PP
.B Website: 
https://haxtheweb.org/
.PP
.B CLI Repository: 
https://github.com/haxtheweb/create
.PP
.B Web Components Repository:
https://github.com/haxtheweb/webcomponents
.PP
.B DDD Design System Documentation
https://haxtheweb.org/documentation/ddd


.SH AUTHORS
.PP
.B CLI Contributors:
https://github.com/haxtheweb/create/graphs/contributors
.PP
.B Web Components Contributors:
https://github.com/haxtheweb/webcomponents/graphs/contributors